name: issues workflow
on: issues
jobs:
    print_some_event_details:
        runs-on: ubuntu-latest
        steps:
            - name: print the details
              run: echo "${{ toJson(github.event.issue)}}"

