name: pull_request-opened
on:
    pull_request:
        types: [opened, reopened, closed]
        branches:
            - main
jobs:
    give_details:
        runs-on: Ubuntu latest
        steps:
            - name: print the details
              run: echo "${{ toJson(github.event)}}"
    
    friendly_text:
        runs-on: Ubuntu-latest
        steps:
            - name: print_some_text
              run: echo "Your code is very usefull!"
            