name: push-workflow
on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  test_code:
    runs-on: ubuntu-latest
    steps:
      - name: get the code
        uses: actions/checkout@v4

      - name: install dependencies
        run: pip install cryptography

      - name: make a key
        run: python create_key.py

      - name: test code
        run: python test.py
      
  Build_and_upload_encryptions:  #encryptions work somewhat like a build that I upload as an artifact, here i also publish some output of the number of encryptiosn
    needs: test_code
    runs-on: ubuntu-latest
    outputs: 
      number_of_lines: ${{steps.counter.outputs.line_count}}
    steps:
      - name: get the code
        uses: actions/checkout@v4

      - name: install dependencies
        run: pip install cryptography

      - name: make a key
        run: python create_key.py

      - name: run code # create the encryptions
        run: python main.py
      
      - name: upload the encryptions
        uses: actions/upload-artifact@v4
        with:
          name: encryptions
          path: ./encrypted_passwords.txt
      
      - name: publish number of encryptions
        id: counter
        run: |
          line_count=$(cat ./encrypted_passwords.txt | wc -l)
          echo "line_count=$line_count" >> "$GITHUB_OUTPUT"
   
  download_and_show_artifact: # this job shocases how to download artiacts and also how to get oututs from another job
    runs-on: Ubuntu-latest
    needs: Build_and_upload_encryptions
    steps:
      - name: download encryptions
        uses: actions/download-artifact@v4
        with:
          name: encryptions
      
      - name: print number of lines from output
        run: echo "this file contains ${{needs.Build_and_upload_encryptions.outputs.number_of_lines}} encrypted passwords"
      
      - name: print_contents
        run: cat ./encrypted_passwords.txt

      

    