name: push-workflow
on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  run_the_code:
    runs-on: ubuntu-latest
    steps:
      - name: get the code
        uses: actions/checkout@v4

      - name: install dependencies
        run: pip install cryptography

      - name: make a key
        run: python create_key.py

      - name: test code
        run: python test.py
      
      - name: run code
        run: python main.py
      
      - name: upload the encryptions
        uses: actions/upload-artifact@v4
        with:
          name: encryptions
          path: ./encrypted_passwords.txt
