name: push-workflow
on: push
jobs:
  run_the_code:
    runs-on: windows-latest
    steps:
      - name: get the code
        uses: actions/checkout@v4
      - name: download dependencies
        run: pip install cryptography
      - name: make a key
        run: python create_key.py
      - name: python main.py
        run: python
