name: push-workflow
on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  run_to_artifact:
    runs-on: ubuntu-latest
    outputs: 
      number_of_lines: ${{steps.line-count.outputs}}
    steps:
      - name: get the code
        uses: actions/checkout@v4

      - name: install dependencies
        run: pip install cryptography

      - name: make a key
        run: python create_key.py

      - name: test code
        run: python test.py
      
      - name: run code
        run: python main.py
      
      - name: upload the encryptions
        uses: actions/upload-artifact@v4
        with:
          name: encryptions
          path: ./encrypted_passwords.txt
      
      - name: publish number of encryptions
        id: line-count
        run: cat ./encrypted_passwords.txt | wc -l >> "$GITHUB_OUTPUT"

  print_information:
    runs-on: Ubuntu-latest
    needs: run_to_artifact
    steps:
      - name: download encryptions
        uses: actions/download-artifact@v4
        with:
          name: encryptions
      
      - name: print_contents
        run: cat ./encrypted_passwords.txt

      

    